source 'https://github.com/gini/gini-podspecs.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.2'

use_frameworks!

def project_pods
    pod 'GiniPayBank', :path => '../', :testspecs => ['Tests']

end

target 'Example Swift' do

    project_pods

    target 'Example_Tests' do
        inherit! :search_paths
    end

    target 'GiniPayBankSDKTests' do
        inherit! :search_paths
    end
end
